// app监听地址
Addr: "0.0.0.0:9090"
WsAddr: "0.0.0.0:9091"

// kubeconfig路径(多集群)
// Kubeconfigs = `{"Cluster-1":"/root/.kube/config","Cluster-2":"/Users/adoo/.kube/config"}`
KubeConfigs: `{"Cluster-1":"/root/.kube/config"}`

// app账号密码
AdminUser: "admin"
AdminPwd: "passwd"

// Pod的日志 tail 显示
PodLogTailLine: 2000
LogDebug: false // 是否打印debug日志
UploadPath: "/root/chart"

//db配置
DB:
  DbType: "mysql"
  DbHost: "127.0.0.1" // "192.168.23.100"
  DbPort: 3306
  DbName: "k8s_abais"
  DbUser: "root"
  DbPwd: "100.Acjq"
  MaxIdleConns: 10               // 最大空闲连接
  MaxOpenConns: 100              // 最大连接数
  MaxLifeTime: 30 * time.Second // 最大生存时间