# app监听地址
Addr: "0.0.0.0:9090"
WsAddr: "0.0.0.0:9091"

read_timeout: 20
write_timeout: 20
max_header: 20
mode: "dev"  # dev prod


# kubeconfig路径(多集群)
# Kubeconfigs = `{"Cluster-1":"/root/.kube/config","Cluster-2":"/Users/adoo/.kube/config"}`
KubeConfigs: '{"Cluster-1":"/root/.kube/config"}'

# 提供app默认账号密码
AdminUser: "admin"
AdminPwd: "passwd"

# Pod的日志 tail 显示
PodLogTailLine: 2000
LogMode: false # 是否打印mysql的debug日志
UploadPath: "/root/chart"

# db配置
DB:
  DbType: "mysql"
  DbHost: "127.0.0.1" # "192.168.23.100"
  DbPort: 3306
  DbName: "k8s_abais"
  DbUser: "root"
  DbPwd: "100.Acjq"
  MaxIdleConns: 10               # 最大空闲连接
  MaxOpenConns: 100              # 最大连接数
  MaxLifeTime: 30                # 最大生存时间

# log配置
log:
  file_name: "./log/aBais.log"  #建议program_name
  level: "debug"  #debug warn info panic fatal dpanic
  max_size: 200  #Mib
  max_age: 10
  max_backup: 10  #份
  compress: true